name: DJ Site Build and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.2

    env:
      CI: false
      REACT_APP_AWS_USER_POOL_ID: ${{ secrets.AWS_USER_POOL_ID }}
      REACT_APP_AWS_REGION: ${{ secrets.AWS_REGION }}
      REACT_APP_AWS_CLIENT_ID: ${{ secrets.AWS_CLIENT_ID }}
      REACT_APP_AWS_IDENTITY_POOL_ID: ${{ secrets.AWS_IDENTITY_POOL_ID }}
      REACT_APP_LAST_FM_KEY: ${{ secrets.LAST_FM_KEY }}
      REACT_APP_DISCOGS_CONSUMER_KEY: ${{ secrets.DISCOGS_CONSUMER_KEY }}
      REACT_APP_DISCOGS_CONSUMER_SECRET: ${{ secrets.DISCOGS_CONSUMER_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
