name: DJ Site Build and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      
      - name: Set up Git user identity
        env:
          GIT_USER_EMAIL: github-actions@github.com
          GIT_USER_NAME: github-actions
          # Add the personal access token as an environment variable
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"
        
      - name: Build and Deploy
        run: npm run deploy

    env:
      CI: false
      REACT_APP_AWS_USER_POOL_ID: ${{ secrets.AWS_USER_POOL_ID }}
      REACT_APP_AWS_REGION: ${{ secrets.AWS_REGION }}
      REACT_APP_AWS_CLIENT_ID: ${{ secrets.AWS_CLIENT_ID }}
      REACT_APP_AWS_IDENTITY_POOL_ID: ${{ secrets.AWS_IDENTITY_POOL_ID }}
      REACT_APP_LAST_FM_KEY: ${{ secrets.LAST_FM_KEY }}
      REACT_APP_DISCOGS_CONSUMER_KEY: ${{ secrets.DISCOGS_CONSUMER_KEY }}
      REACT_APP_DISCOGS_CONSUMER_SECRET: ${{ secrets.DISCOGS_CONSUMER_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
